import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const STATE_PREFIX_MAP = new Map([
  ["default", ""],
  ["hover", "hover:"],
  ["active", "active:"],
  ["focus", "focus:"],
]);
const THEME_PREFIX_MAP = new Map([
  ["light", ""],
  ["dark", "dark:"],
]);

function formatStates(
  entity: string,
  palette: string,
  states: string[],
  themes: string[]
) {
  return states
    .map((s) => {
      const themeFormatted = themes
        .map((t) => {
          return `${THEME_PREFIX_MAP.get(t)}${STATE_PREFIX_MAP.get(s)}${entity}-(--plt-${palette.toLowerCase()}-${entity}-${t}-${s})`;
        })
        .join(" ");

      return `${s.toUpperCase()}:"${themeFormatted}"`;
    })
    .join(",\n");
}

const generatedName = "COLOR_GENERATED_PALETTES_CLASSES";
const fileName = "autoGeneratedPalettesClasses.ts";

export default async function generatePalettesStyles(
  entities: string[],
  themes: string[],
  states: string[],
  palettes: string[]
) {
  const fileToGenerate = resolve(
    process.cwd(),
    "app",
    "constants",
    "color",
    fileName
  );

  const palettesFormatted = palettes
    .map((p) => {
      const entitiesFormatted = entities
        .map((e) => {
          return `${e.toUpperCase()}:{${formatStates(e, p, states, themes)}}`;
        })
        .join(",\n");

      return `${p.toUpperCase()}: {${entitiesFormatted}}`;
    })
    .join(",\n");

  const content = `/** All color palettes, that used in project */\nconst ${generatedName} = {\n${palettesFormatted}\n};\nexport default COLOR_GENERATED_PALETTES_CLASSES`;

  await mkdir(dirname(fileToGenerate), { recursive: true });
  await writeFile(fileToGenerate, content, "utf-8");

  console.log("Successful generate", fileToGenerate);
}
