import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const generatedName = "ColorGeneratedPalettes";
const fileName = "autoGeneratedPalettes.ts";

const fileToGenerate = resolve(
  process.cwd(),
  "app",
  "types",
  "color",
  fileName
);

/** used to generate color palettes as types for usage in project */
export default async function generateColorPalettesType(palettes: string[]) {
  const formattedPalettes = palettes
    .map((p) => `"${p.toUpperCase()}"`)
    .join("|");
  const colorPalettesTypeContent = `export type ${generatedName} = ${formattedPalettes};`;

  await mkdir(dirname(fileToGenerate), { recursive: true });
  await writeFile(fileToGenerate, colorPalettesTypeContent, "utf-8");

  console.log("Successful generate", fileToGenerate);
}
