import type { StateTypes } from "~/types/state";
import type { Icons } from "./icons/autoGenerated";

export type IconState = Extract<
  StateTypes,
  "default" | "hover" | "active" | "disabled"
>;

export type IconProps = {
  /** State type of icon for styling */
  state: IconState;
  type: Icons;
};
