import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const toWritePath = resolve(
  process.cwd(),
  "app",
  "components",
  "ui",
  "Icon",
  "icons",
  "autoGenerated.ts"
);

export default async function () {
  const icons = (
    await readdir(
      resolve(process.cwd(), "app", "components", "ui", "Icon", "icons"),
      "utf-8"
    )
  ).filter((i) => i.includes(".vue"));

  const toWriteContent = [
    "/** All added icons to project */",
    `export type Icons = ${icons.map((i) => `"${i.replace(".vue", "").toLowerCase()}"`).join("|")};`,
    "const iconMap = new Map<Icons, Component>([",
    ...icons.map(
      (i) =>
        `  ["${i.replace(".vue", "").toLowerCase()}", defineAsyncComponent(() => import("./${i}"))],`
    ),
    "]);",
    "export default iconMap;",
    "",
  ].join("\n");

  await mkdir(dirname(toWritePath), { recursive: true });
  await writeFile(toWritePath, toWriteContent, "utf-8");

  console.log(`Successful generate ${toWritePath}`);
}
